ignore:
  - "src/accounting/oracles/ERC7540YieldSourceOracle.sol"
  - "src/hooks/claim/gearbox/**"
  - "src/hooks/claim/yearn/**"
  - "src/hooks/claim/fluid/**"
  - "src/hooks/loan/morpho/**"
  - "src/hooks/stake/**"
  - "src/hooks/swappers/spectra/**"
  - "src/hooks/swappers/uniswap-v4/**"
  - "src/hooks/vaults/vault-bank/**"
  - "src/vendor/**"
  - "test/**"