include version.mk

# Check for required dependencies
CHECK_MOCKERY := $(shell command -v mockery 2> /dev/null)
CHECK_GO := $(shell command -v go 2> /dev/null)
CHECK_DOCKER := $(shell command -v docker 2> /dev/null)
CHECK_CURL := $(shell command -v curl 2> /dev/null)
CHECK_SOLC := $(shell command -v solc 2> /dev/null)
CHECK_ABIGEN := $(shell command -v abigen 2> /dev/null)

check-mockery:
ifndef CHECK_MOCKERY
	$(error "Mockery is not installed. Please install Mockery and retry.")
endif

check-go:
ifndef CHECK_GO
	$(error "Go is not installed. Please install Go and retry.")
endif

check-docker:
ifndef CHECK_DOCKER
	$(error "Docker is not installed. Please install Docker and retry.")
endif

check-curl:
ifndef CHECK_CURL
	$(error "curl is not installed. Please install curl and retry.")
endif

check-solc:
ifndef CHECK_SOLC
	$(error "Solc is not installed. Please install solc and retry.")
endif

check-abigen:
ifndef CHECK_ABIGEN
	$(error "Abigen is not installed. Please install Abigen and retry.")
endif

# Targets that require the checks
generate: check-mockery check-solc check-abigen
gobindings: check-solc check-abigen
build: check-go
build-docker: check-docker
build-docker-nc: check-docker
install-linter: check-go check-curl
lint: check-go

ARCH := $(shell uname -m)

ifeq ($(ARCH),x86_64)
	ARCH = amd64
else
	ifeq ($(ARCH),aarch64)
		ARCH = arm64
	endif
endif

GOBASE := $(shell pwd)
GOBIN := $(GOBASE)/dist
GOOS := $(shell uname -s  | tr '[:upper:]' '[:lower:]')
GOENVVARS := GOBIN=$(GOBIN) CGO_ENABLED=0 GOOS=$(GOOS) GOARCH=$(ARCH)
GOBINARY := relayer
GOCMD := $(GOBASE)/cmd

LDFLAGS += -X 'github.com/superform-xyz/v2-core.Version=$(VERSION)'
LDFLAGS += -X 'github.com/superform-xyz/v2-core.GitRev=$(GITREV)'
LDFLAGS += -X 'github.com/superform-xyz/v2-core.GitBranch=$(GITBRANCH)'
LDFLAGS += -X 'github.com/superform-xyz/v2-core.BuildDate=$(DATE)'

.PHONY: generate
generate: gobindings ## Generates mocks and other autogenerated types
	mockery

.PHONY: gobindings
gobindings: ## Generates go bindings for smart contracts
	mkdir -p ./pkg/contracts/build

	# Generate go bindings for Foo.sol contract
	solc --abi ./contracts/src/Foo.sol --bin ./contracts/src/Foo.sol -o ./pkg/contracts/build --overwrite
	abigen --abi ./pkg/contracts/build/Foo.abi \
		   --bin ./pkg/contracts/build/Foo.bin \
		   --pkg contracts \
		   --type Foo \
		   --out ./pkg/contracts/Foo.go

	rm -rf ./pkg/contracts/build

.PHONY: build
build: ## Builds the binary locally into ./dist
	$(GOENVVARS) go build -ldflags "all=$(LDFLAGS)" -o $(GOBIN)/$(GOBINARY) $(GOCMD)

.PHONY: build-docker
build-docker: ## Builds a docker image
	docker build -t superform-v2-relayer -f ./Dockerfile .

.PHONY: build-docker-nc
build-docker-nc: ## Builds a docker image - but without build cache
	docker build --no-cache=true -t superform-v2-relayer -f ./Dockerfile .

.PHONY: install-linter
install-linter: ## Installs the linter
	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $$(go env GOPATH)/bin v1.59.1

.PHONY: lint
lint: ## Runs the linter
	golangci-lint run

.PHONY: test-unit
test-unit: ## Runs the unit tests
	go test -v ./... -short

## Help display.
## Pulls comments from beside commands and prints a nicely formatted
## display with the commands and their usage information.
.DEFAULT_GOAL := help

.PHONY: help
help: ## Prints this help
		@grep -h -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
