// SPDX-License-Identifier: Apache-2.0
pragma solidity >=0.8.30;

import { DeployV2Base } from "./DeployV2Base.s.sol";
import { ConfigOtherHooks } from "./utils/ConfigOtherHooks.sol";

import { Strings } from "openzeppelin-contracts/contracts/utils/Strings.sol";
import { console2 } from "forge-std/console2.sol";

contract DeployV2OtherHooks is DeployV2Base, ConfigOtherHooks {
    struct OtherHookAddresses {
        address fluidClaimRewardHook;
        address gearboxClaimRewardHook;
        address yearnClaimOneRewardHook;
        address gearboxStakeHook;
        address approveAndGearboxStakeHook;
        address gearboxUnstakeHook;
        address fluidStakeHook;
        address approveAndFluidStakeHook;
        address fluidUnstakeHook;
        address spectraExchangeDepositHook;
        address spectraExchangeRedeemHook;
        address pendleRouterSwapHook;
        address pendleRouterRedeemHook;
        address morphoSupplyAndBorrowHook;
        address morphoRepayHook;
        address morphoRepayAndWithdrawHook;
        address morphoBorrowHook;
    }

    struct HookDeployment {
        string name;
        bytes creationCode;
    }

    /// @notice Sets up complete configuration for other hooks deployment
    /// @param env Environment (0/2 = production, 1 = test)
    /// @param saltNamespace Salt namespace for deployment (if empty, uses production default)
    function _setConfiguration(uint256 env, string memory saltNamespace) internal {
        // Set base configuration (chain names, common addresses)
        _setBaseConfiguration(env, saltNamespace);

        // Set protocol router addresses for hooks
        _setOtherHooksConfiguration();
    }

    function run(uint256 env, uint64 chainId) public broadcast(env) {
        _setConfiguration(env, "");
        console2.log("Deploying V2 Other Hooks on chainId: ", chainId);

        // deploy other hooks
        _deployOtherHooks(chainId, env);

        // Write all exported contracts for this chain
        _writeExportedContracts(chainId);
    }

    function run(uint256 env, uint64 chainId, string memory saltNamespace) public broadcast(env) {
        _setConfiguration(env, saltNamespace);
        console2.log("Deploying V2 Other Hooks on chainId: ", chainId);

        // deploy other hooks
        _deployOtherHooks(chainId, env);

        // Write all exported contracts for this chain
        _writeExportedContracts(chainId);
    }

    /// @notice Get bytecode directory for other hooks based on environment
    /// @param env Environment (1 = vnet/dev, 0/2 = prod/staging)
    /// @return bytecodeDir Directory path for other hooks bytecode artifacts
    function __getOtherHooksBytecodeDirectory(uint256 env) internal pure returns (string memory) {
        if (env == 1) {
            // VNET environment - use generated bytecode
            return "script/generated-bytecode-other/";
        } else {
            // Production/Staging environment - use locked bytecode
            return "script/locked-bytecode-other/";
        }
    }

    /// @notice Get bytecode from environment-specific artifacts for other hooks
    /// @param contractName Name of the contract
    /// @param env Environment (1 = vnet/dev, 0/2 = prod/staging)
    /// @return bytecode Contract bytecode
    function __getOtherHooksBytecode(string memory contractName, uint256 env) internal returns (bytes memory) {
        string memory artifactPath =
            string(abi.encodePacked(__getOtherHooksBytecodeDirectory(env), contractName, ".json"));
        return vm.getCode(artifactPath);
    }

    function _deployOtherHooks(uint64 chainId, uint256 env) internal {
        // Deploy Other Hooks
        _deployHooksSet(chainId, env);
    }

    function _deployHooksSet(uint64 chainId, uint256 env) private returns (OtherHookAddresses memory hookAddresses) {
        uint256 len = 17;
        HookDeployment[] memory hooks = new HookDeployment[](len);
        address[] memory addresses = new address[](len);

        // Claim hooks
        hooks[0] = HookDeployment(FLUID_CLAIM_REWARD_HOOK_KEY, __getOtherHooksBytecode("FluidClaimRewardHook", env));
        hooks[1] = HookDeployment(GEARBOX_CLAIM_REWARD_HOOK_KEY, __getOtherHooksBytecode("GearboxClaimRewardHook", env));
        hooks[2] =
            HookDeployment(YEARN_CLAIM_ONE_REWARD_HOOK_KEY, __getOtherHooksBytecode("YearnClaimOneRewardHook", env));

        // Stake hooks
        hooks[3] = HookDeployment(FLUID_STAKE_HOOK_KEY, __getOtherHooksBytecode("FluidStakeHook", env));
        hooks[4] =
            HookDeployment(APPROVE_AND_FLUID_STAKE_HOOK_KEY, __getOtherHooksBytecode("ApproveAndFluidStakeHook", env));
        hooks[5] = HookDeployment(FLUID_UNSTAKE_HOOK_KEY, __getOtherHooksBytecode("FluidUnstakeHook", env));
        hooks[6] = HookDeployment(GEARBOX_STAKE_HOOK_KEY, __getOtherHooksBytecode("GearboxStakeHook", env));
        hooks[7] = HookDeployment(
            GEARBOX_APPROVE_AND_STAKE_HOOK_KEY, __getOtherHooksBytecode("ApproveAndGearboxStakeHook", env)
        );
        hooks[8] = HookDeployment(GEARBOX_UNSTAKE_HOOK_KEY, __getOtherHooksBytecode("GearboxUnstakeHook", env));

        // Spectra swapper hooks
        hooks[9] = HookDeployment(
            SPECTRA_EXCHANGE_DEPOSIT_HOOK_KEY,
            abi.encodePacked(
                __getOtherHooksBytecode("SpectraExchangeDepositHook", env),
                abi.encode(otherHooksConfiguration.spectraRouters[chainId])
            )
        );
        hooks[10] = HookDeployment(
            SPECTRA_EXCHANGE_REDEEM_HOOK_KEY,
            abi.encodePacked(
                __getOtherHooksBytecode("SpectraExchangeRedeemHook", env),
                abi.encode(otherHooksConfiguration.spectraRouters[chainId])
            )
        );

        // Pendle swapper hooks
        hooks[11] = HookDeployment(
            PENDLE_ROUTER_SWAP_HOOK_KEY,
            abi.encodePacked(
                __getOtherHooksBytecode("PendleRouterSwapHook", env),
                abi.encode(otherHooksConfiguration.pendleRouters[chainId])
            )
        );
        hooks[12] = HookDeployment(
            PENDLE_ROUTER_REDEEM_HOOK_KEY,
            abi.encodePacked(
                __getOtherHooksBytecode("PendleRouterRedeemHook", env),
                abi.encode(otherHooksConfiguration.pendleRouters[chainId])
            )
        );

        // Morpho loan hooks
        hooks[13] = HookDeployment(
            MORPHO_SUPPLY_AND_BORROW_HOOK_KEY,
            abi.encodePacked(__getOtherHooksBytecode("MorphoSupplyAndBorrowHook", env), abi.encode(MORPHO))
        );
        hooks[14] = HookDeployment(
            MORPHO_REPAY_HOOK_KEY, abi.encodePacked(__getOtherHooksBytecode("MorphoRepayHook", env), abi.encode(MORPHO))
        );
        hooks[15] = HookDeployment(
            MORPHO_REPAY_AND_WITHDRAW_HOOK_KEY,
            abi.encodePacked(__getOtherHooksBytecode("MorphoRepayAndWithdrawHook", env), abi.encode(MORPHO))
        );
        hooks[16] = HookDeployment(
            MORPHO_BORROW_ONLY_HOOK_KEY,
            abi.encodePacked(__getOtherHooksBytecode("MorphoBorrowHook", env), abi.encode(MORPHO))
        );

        for (uint256 i = 0; i < len; ++i) {
            HookDeployment memory hook = hooks[i];
            addresses[i] = __deployContract(hook.name, chainId, __getSalt(hook.name), hook.creationCode);
        }

        // Assign hook addresses
        hookAddresses.fluidClaimRewardHook =
            Strings.equal(hooks[0].name, FLUID_CLAIM_REWARD_HOOK_KEY) ? addresses[0] : address(0);
        hookAddresses.gearboxClaimRewardHook =
            Strings.equal(hooks[1].name, GEARBOX_CLAIM_REWARD_HOOK_KEY) ? addresses[1] : address(0);
        hookAddresses.yearnClaimOneRewardHook =
            Strings.equal(hooks[2].name, YEARN_CLAIM_ONE_REWARD_HOOK_KEY) ? addresses[2] : address(0);
        hookAddresses.fluidStakeHook = Strings.equal(hooks[3].name, FLUID_STAKE_HOOK_KEY) ? addresses[3] : address(0);
        hookAddresses.approveAndFluidStakeHook =
            Strings.equal(hooks[4].name, APPROVE_AND_FLUID_STAKE_HOOK_KEY) ? addresses[4] : address(0);
        hookAddresses.fluidUnstakeHook =
            Strings.equal(hooks[5].name, FLUID_UNSTAKE_HOOK_KEY) ? addresses[5] : address(0);
        hookAddresses.gearboxStakeHook =
            Strings.equal(hooks[6].name, GEARBOX_STAKE_HOOK_KEY) ? addresses[6] : address(0);
        hookAddresses.approveAndGearboxStakeHook =
            Strings.equal(hooks[7].name, GEARBOX_APPROVE_AND_STAKE_HOOK_KEY) ? addresses[7] : address(0);
        hookAddresses.gearboxUnstakeHook =
            Strings.equal(hooks[8].name, GEARBOX_UNSTAKE_HOOK_KEY) ? addresses[8] : address(0);
        hookAddresses.spectraExchangeDepositHook =
            Strings.equal(hooks[9].name, SPECTRA_EXCHANGE_DEPOSIT_HOOK_KEY) ? addresses[9] : address(0);
        hookAddresses.spectraExchangeRedeemHook =
            Strings.equal(hooks[10].name, SPECTRA_EXCHANGE_REDEEM_HOOK_KEY) ? addresses[10] : address(0);
        hookAddresses.pendleRouterSwapHook =
            Strings.equal(hooks[11].name, PENDLE_ROUTER_SWAP_HOOK_KEY) ? addresses[11] : address(0);
        hookAddresses.pendleRouterRedeemHook =
            Strings.equal(hooks[12].name, PENDLE_ROUTER_REDEEM_HOOK_KEY) ? addresses[12] : address(0);
        hookAddresses.morphoSupplyAndBorrowHook =
            Strings.equal(hooks[13].name, MORPHO_SUPPLY_AND_BORROW_HOOK_KEY) ? addresses[13] : address(0);
        hookAddresses.morphoRepayHook =
            Strings.equal(hooks[14].name, MORPHO_REPAY_HOOK_KEY) ? addresses[14] : address(0);
        hookAddresses.morphoRepayAndWithdrawHook =
            Strings.equal(hooks[15].name, MORPHO_REPAY_AND_WITHDRAW_HOOK_KEY) ? addresses[15] : address(0);
        hookAddresses.morphoBorrowHook =
            Strings.equal(hooks[16].name, MORPHO_BORROW_ONLY_HOOK_KEY) ? addresses[16] : address(0);

        // Verify no hooks were assigned address(0)
        require(hookAddresses.fluidClaimRewardHook != address(0), "fluidClaimRewardHook not assigned");
        require(hookAddresses.gearboxClaimRewardHook != address(0), "gearboxClaimRewardHook not assigned");
        require(hookAddresses.yearnClaimOneRewardHook != address(0), "yearnClaimOneRewardHook not assigned");
        require(hookAddresses.fluidStakeHook != address(0), "fluidStakeHook not assigned");
        require(hookAddresses.approveAndFluidStakeHook != address(0), "approveAndFluidStakeHook not assigned");
        require(hookAddresses.fluidUnstakeHook != address(0), "fluidUnstakeHook not assigned");
        require(hookAddresses.gearboxStakeHook != address(0), "gearboxStakeHook not assigned");
        require(hookAddresses.approveAndGearboxStakeHook != address(0), "approveAndGearboxStakeHook not assigned");
        require(hookAddresses.gearboxUnstakeHook != address(0), "gearboxUnstakeHook not assigned");
        require(hookAddresses.spectraExchangeDepositHook != address(0), "spectraExchangeDepositHook not assigned");
        require(hookAddresses.spectraExchangeRedeemHook != address(0), "spectraExchangeRedeemHook not assigned");
        require(hookAddresses.pendleRouterSwapHook != address(0), "pendleRouterSwapHook not assigned");
        require(hookAddresses.pendleRouterRedeemHook != address(0), "pendleRouterRedeemHook not assigned");
        require(hookAddresses.morphoSupplyAndBorrowHook != address(0), "MorphoSupplyAndBorrowHook not assigned");
        require(hookAddresses.morphoRepayHook != address(0), "morphoRepayHook not assigned");
        require(hookAddresses.morphoRepayAndWithdrawHook != address(0), "morphoRepayAndWithdrawHook not assigned");
        require(hookAddresses.morphoBorrowHook != address(0), "morphoBorrowHook not assigned");

        console2.log("All other hooks deployed and validated successfully.");

        return hookAddresses;
    }
}
