#!/usr/bin/env python3
"""
Compute new CREATE2 addresses for hooks with regenerated bytecodes
and update the deployment JSON files.

Hooks affected: 9 Morpho + 2 OdosV3 = 11 hooks
"""

import json
import os
import subprocess
import sys

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "../.."))
LOCKED_BYTECODE_DIR = os.path.join(PROJECT_ROOT, "script/locked-bytecode-other")
OUTPUT_DIR = os.path.join(PROJECT_ROOT, "script/output/prod")

DEPLOYER = "0x4e59b44847b379578588920cA78FbF26c0B4956C"

# Morpho addresses per chain (from ConstantsOtherHooks.sol)
MORPHO_ADDRESSES = {
    1: "0xBBBBBbbBBb9cC5e90e3b3Af64bdAF62C37EEFFCb",
    56: "0x01b0Bd309AA75547f7a37Ad7B1219A898E67a83a",
    8453: "0xBBBBBbbBBb9cC5e90e3b3Af64bdAF62C37EEFFCb",
    42161: "0x6c247b1F6182318877311737BaC0844bAa518F5e",
}

# Odos V3 router (same on all chains)
ODOS_ROUTER_V3 = "0x0D05a7D3448512B78fa8A9e46c4872C88C4a0D05"

# Chain ID -> (network name, JSON filename pattern)
CHAINS = {
    1: "Ethereum-latest.json",
    56: "BNB-latest.json",
    8453: "Base-latest.json",
    42161: "Arbitrum-latest.json",
}

# Hooks with constructor args (Morpho address)
MORPHO_CONSTRUCTOR_HOOKS = [
    "MorphoSupplyAndBorrowHook",
    "MorphoBorrowHook",
    "MorphoRepayHook",
    "MorphoRepayAndWithdrawHook",
    "MorphoSupplyHook",
    "MorphoWithdrawHook",
    "MorphoLendHook",
]

# Hooks without constructor args
MORPHO_NO_CONSTRUCTOR_HOOKS = [
    "MetaMorphoReallocateHook",
    "ForceDeallocateMorphoHook",
]

# OdosV3 hooks (constructor: address routerV3)
ODOS_V3_HOOKS = [
    "SwapOdosV3Hook",
    "ApproveAndSwapOdosV3Hook",
]


def cast_keccak(hex_data: str) -> str:
    """Run cast keccak on hex data and return the hash."""
    result = subprocess.run(
        ["cast", "keccak", hex_data],
        capture_output=True, text=True, check=True
    )
    return result.stdout.strip()


def cast_from_utf8(text: str) -> str:
    """Convert text to hex using cast."""
    result = subprocess.run(
        ["cast", "--from-utf8", text],
        capture_output=True, text=True, check=True
    )
    return result.stdout.strip()


def cast_to_checksum(addr: str) -> str:
    """Convert address to checksum format."""
    result = subprocess.run(
        ["cast", "to-check-sum-address", addr],
        capture_output=True, text=True, check=True
    )
    return result.stdout.strip()


def compute_salt(hook_name: str) -> str:
    """Compute salt: keccak256(abi.encodePacked("SuperformV2", "", hookName, "v2.0"))"""
    text = f"SuperformV2{hook_name}v2.0"
    hex_data = cast_from_utf8(text)
    return cast_keccak(hex_data)


def get_bytecode(hook_name: str) -> str:
    """Get bytecode from locked-bytecode-other/<hookName>.json"""
    path = os.path.join(LOCKED_BYTECODE_DIR, f"{hook_name}.json")
    with open(path) as f:
        data = json.load(f)
    bc = data["bytecode"]["object"]
    if not bc.startswith("0x"):
        bc = "0x" + bc
    return bc


def abi_encode_address(addr: str) -> str:
    """ABI encode an address (left-pad to 32 bytes)."""
    addr_clean = addr.lower().replace("0x", "")
    return addr_clean.zfill(64)


def compute_create2_address(salt: str, init_code: str) -> str:
    """
    Compute CREATE2 address:
    keccak256(0xff ++ deployer ++ salt ++ keccak256(initCode))[12:]
    """
    init_code_hash = cast_keccak(init_code)

    deployer_hex = DEPLOYER[2:].lower()
    salt_hex = salt[2:].lower()
    hash_hex = init_code_hash[2:].lower()

    preimage = f"0xff{deployer_hex}{salt_hex}{hash_hex}"
    result_hash = cast_keccak(preimage)

    # Take last 20 bytes (40 hex chars)
    addr = "0x" + result_hash[-40:]
    return cast_to_checksum(addr)


def compute_hook_address(hook_name: str, constructor_arg_hex: str = "") -> str:
    """Compute the CREATE2 address for a hook."""
    salt = compute_salt(hook_name)
    bytecode = get_bytecode(hook_name)

    if constructor_arg_hex:
        bc_hex = bytecode[2:]
        init_code = f"0x{bc_hex}{constructor_arg_hex}"
    else:
        init_code = bytecode

    return compute_create2_address(salt, init_code)


def update_json(chain_id: int, updates: dict):
    """Update a deployment JSON file with new addresses."""
    json_path = os.path.join(OUTPUT_DIR, str(chain_id), CHAINS[chain_id])
    if not os.path.exists(json_path):
        print(f"  WARNING: {json_path} not found, skipping")
        return

    with open(json_path) as f:
        data = json.load(f)

    changed = []
    for hook_name, new_addr in updates.items():
        old_addr = data.get(hook_name, "NOT_FOUND")
        if old_addr != new_addr:
            changed.append((hook_name, old_addr, new_addr))
            data[hook_name] = new_addr
        else:
            print(f"  {hook_name}: unchanged ({new_addr})")

    if changed:
        with open(json_path, "w") as f:
            json.dump(data, f, indent=2, sort_keys=True)
            f.write("\n")
        for hook_name, old_addr, new_addr in changed:
            print(f"  {hook_name}: {old_addr} -> {new_addr}")
    else:
        print(f"  No changes needed for chain {chain_id}")


def main():
    print("Computing new CREATE2 addresses for regenerated hooks...")
    print(f"Deployer: {DEPLOYER}")
    print()

    for chain_id, json_file in CHAINS.items():
        print(f"=== Chain {chain_id} ({json_file}) ===")
        updates = {}

        # Morpho hooks with constructor args
        morpho_addr = MORPHO_ADDRESSES.get(chain_id)
        if morpho_addr:
            morpho_arg_hex = abi_encode_address(morpho_addr)
            for hook_name in MORPHO_CONSTRUCTOR_HOOKS:
                addr = compute_hook_address(hook_name, morpho_arg_hex)
                updates[hook_name] = addr

            # Morpho hooks without constructor args
            for hook_name in MORPHO_NO_CONSTRUCTOR_HOOKS:
                addr = compute_hook_address(hook_name)
                updates[hook_name] = addr

        # OdosV3 hooks (all 4 chains have OdosV3)
        odos_arg_hex = abi_encode_address(ODOS_ROUTER_V3)
        for hook_name in ODOS_V3_HOOKS:
            addr = compute_hook_address(hook_name, odos_arg_hex)
            updates[hook_name] = addr

        update_json(chain_id, updates)
        print()

    print("Done! Run smoke tests to verify.")


if __name__ == "__main__":
    main()
