with-expecter: true
dir: "./mocks"
filename: "{{.InterfaceName | lower }}.generated.go"
mockname: "{{.InterfaceName}}"
outpkg: "mocks"
packages:
  github.com/superform-xyz/v2-core/relayer/pkg/txmngr:
    config:
    interfaces:
      EthClient:
        config:
          mockname: EthClient
          filename: ethclient.generated.go